
# Conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_prueba_jcm
spring.datasource.username=postgres
spring.datasource.password=123

# Hibernate: Esto creará o actualizará automáticamente las tablas en la BD según tu código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true